version: '3.7'

services:
  db:
    image: mariadb:10.1.45
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MaSuperAgenceIpi
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './apps/MaSuperAgence/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    restart: on-failure
    user: 1000:1000
    depends_on:
      - db