# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # configure resolvers
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public/images/properties"

  filter_sets:
    thumb:
      data_loader: default
      cache: default
      quality: 100
      filters:
        thumbnail:
          size:           [348, 196]
          mode:           outbound
    medium:
      data_loader: default
      cache: default
      quality: 100
      filters:
        thumbnail:
          size:           [730, 411]
          mode:           outbound
    home:
      data_loader: default
      cache: default
      quality: 100
      filters:
        thumbnail:
          size:           [230, 120]
          mode:           outbound